version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/udhuhsdfuhs126hifds
    volumes:
      - neo4j_data:/data
    networks:
      - movieweb_net
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -a bolt://localhost:7687 -u neo4j -p udhuhsdfuhs126hifds 'RETURN 1' || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10

  neo4j-init:
    image: neo4j:5
    container_name: neo4j-init
    volumes:
      - ./db:/workspace
    entrypoint: ["cypher-shell", "-a", "bolt://neo4j:7687", "-u", "neo4j", "-p", "udhuhsdfuhs126hifds", "-f", "/workspace/init.cypher"]
    networks:
      - movieweb_net
    depends_on:
      neo4j:
        condition: service_healthy
  
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: app.py
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: udhuhsdfuhs126hifds
    depends_on:
      neo4j-init:
        condition: service_completed_successfully
    networks:
      - movieweb_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 10

  add-users:
    image: python:3.11-slim
    container_name: add_users
    working_dir: /app
    volumes:
      - ./db:/app
    environment:
      BASE_URL: "http://flask-app:5000"
    command: ["sh", "-c", "pip install --no-cache-dir requests && python create_users_api.py"]
    networks:
      - movieweb_net
    restart: "no"
    depends_on:
      flask-app:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: movieweb
    ports:
      - "8080:5173"
    environment:
      VITE_BACKEND_REST_URL: "http://flask-app:5000"
      VITE_BACKEND_GRAPHQL_URL: "http://flask-app:5000"
    depends_on:
      flask-app:
        condition: service_healthy
      add-users:
        condition: service_completed_successfully
    networks:
      - movieweb_net

volumes:
  neo4j_data:

networks:
  movieweb_net:
    driver: bridge

