services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    restart: always
    ports:
      - "7474:7474"   # interfejs webowy
      - "7687:7687"   # port Bolt
    environment:
      NEO4J_AUTH: neo4j/udhuhsdfuhs126hifds
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:

